# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                      Playbook for HANA DB Install                           |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:        scs                                   # TODO: Replace this with new inventory group; Change to correct group
  name:         DB Installation - HANA
  remote_user:  azureadm                              # TODO: Replace with variable
  become:       yes
  become_user:  root
  vars_files:
    - vars/ansible-input-api.yaml                     # DONE: move this back into Repo Structure as an API template


  tasks:

  - name: Test Connection                             # TODO: Temp place holder
    ping:







...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
