---

# TODO: 
# Remove YAML shorthand style for roles (Eg. - { role: os-preparation }) 
# And replace with newer syntax on https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html

- hosts: localhost
  become: true
  become_user: root
  pre_tasks:
    - name: Include output JSON
      include_vars:
        file: "/home/{{ ansible_user }}/output.json"
        name: output

    - name: Create dictionary with HANA database inforamtion from output.JSON
      set_fact:
        hana_database: "{{ item }}"
      loop: "{{ output.databases|flatten(levels=1) }}"
      when: item.platform == 'HANA'

# Prepare os, disks and mount points on Hana Database servers
- hosts: hanadbnodes
  become: true
  become_user: root
  vars_files: 
     - "vars/packages.yml" 
  pre_tasks:
    - name: Include SAP HANA DB sizes
      include_vars:
        file: ../hdb_sizes.json
        name: hdb_sizes
  roles:
    - { role: os-preparation }
    - { role: os-disk-setup }
    - role: enable-prometheus
      when:
        - output.options.enable_prometheus == True
        - ansible_facts['distribution_file_variety'] == 'SUSE'
        - ansible_facts['distribution_version'] is regex("(12.[3-4]|15.\d)")

# Mount Azure File share on all linux servers
- hosts: all_linux_servers
  become: true
  become_user: root
  roles:
    - { role: mount-azure-files, when: output.software.storage_account_sapbits.file_share_name != "" }

# Download SAP Media on Azure File Share
- hosts: localhost
  connection: local
  become: true
  become_user: root
  roles:
    - { role: sap-media-download }

# Hana DB components install 
- hosts: hanadbnodes
  become: true
  become_user: root
  roles: 
    - { role: hdb-server-install }

# Linux jumpboxes components install
- hosts: jumpboxes_linux
  become: true
  become_user: root
  roles: 
    - { role: linux-jumpboxes-install }

# Windows jumpboxes components install
- hosts: jumpboxes_windows
  roles: 
    - { role: windows-jumpboxes-install }
